! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_Monitor.f90
! Time                 : Thu Nov  8 00:02:58 2018
! Working directory    : /net/seasasfs02/srv/export/seasasfs02/share_root/lshen/GC_speedup/github/github_GC_v12/Code.GC12/KPP/Standard
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Monitor


  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: SPC_NAMES_0 = (/ &
     'CH2I2          ','CH2ICl         ','CH2IBr         ', & ! index 1 - 3
     'LSHENA         ','AERI           ','CO2            ', & ! index 4 - 6
     'INDIOL         ','ISALA          ','ISALC          ', & ! index 7 - 9
     'ISN1OA         ','ISN1OG         ','LBRO2H         ', & ! index 10 - 12
     'LBRO2N         ','LISOPOH        ','LISOPNO3       ', & ! index 13 - 15
     'LTRO2H         ','LTRO2N         ','LVOCOA         ', & ! index 16 - 18
     'LVOC           ','LXRO2H         ','LXRO2N         ', & ! index 19 - 21
     'MSA            ','PYAC           ','SO4H1          ', & ! index 22 - 24
     'SO4H2          ','SOAGX          ','SOAIE          ', & ! index 25 - 27
     'SOAME          ','IMAE           ','SOAMG          ', & ! index 28 - 30
     'LSHENE         ','POx            ','LOx            ', & ! index 31 - 33
     'PCO            ','LCO            ','PSO4           ', & ! index 34 - 36
     'LCH4           ','I2O4           ','LSHEND         ', & ! index 37 - 39
     'LSHENB         ','LSHENC         ','LSHENF         ', & ! index 40 - 42
     'DHDN           ','DHDC           ','I2O2           ', & ! index 43 - 45
     'MONITA         ','BENZ           ','CH3CCl3        ', & ! index 46 - 48
     'H1301          ','H2402          ','I2O3           ', & ! index 49 - 51
     'CH3I           ','PMNN           ','PPN            ', & ! index 52 - 54
     'TOLU           ','BrNO2          ','CCl4           ', & ! index 55 - 57
     'CFC11          ','CFC12          ','CFC113         ', & ! index 58 - 60
     'CFC114         ','CFC115         ','H1211          ', & ! index 61 - 63
     'IBr            ','IEPOXD         ','INO            ', & ! index 64 - 66
     'N2O            ','TRO2           ','BRO2           ', & ! index 67 - 69
     'IEPOXA         ','IEPOXB         ','IONITA         ', & ! index 70 - 72
     'N              ','OCS            ','XRO2           ', & ! index 73 - 75
     'HI             ','MAP            ','Cl2O2          ', & ! index 76 - 78
     'ICl            ','IMAO3          ','MPN            ', & ! index 79 - 81
     'CHBr3          ','CHCl3          ','CH2Br2         ', & ! index 82 - 84
     'CH2Cl2         ','ClNO2          ','HCFC142b       ', & ! index 85 - 87
     'IONO           ','HCFC22         ','HCFC123        ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: SPC_NAMES_1 = (/ &
     'OIO            ','RA3P           ','RB3P           ', & ! index 91 - 93
     'DMS            ','XYLE           ','HCFC141b       ', & ! index 94 - 96
     'ETP            ','CH3Br          ','CH3Cl          ', & ! index 97 - 99
     'HNO4           ','ClOO           ','HNO2           ', & ! index 100 - 102
     'OClO           ','PAN            ','RP             ', & ! index 103 - 105
     'PP             ','PRPN           ','SO4            ', & ! index 106 - 108
     'ALK4           ','HPALD          ','PIP            ', & ! index 109 - 111
     'R4P            ','BrCl           ','DHPCARP        ', & ! index 112 - 114
     'C3H8           ','HPC52O2        ','HOI            ', & ! index 115 - 117
     'Br2            ','VRP            ','IAP            ', & ! index 118 - 120
     'HC187          ','ATOOH          ','MOBA           ', & ! index 121 - 123
     'DHMOB          ','HONIT          ','RIPB           ', & ! index 124 - 126
     'MP             ','ISNP           ','BrSALA         ', & ! index 127 - 129
     'BrSALC         ','MAOP           ','MRP            ', & ! index 130 - 132
     'RIPA           ','RIPD           ','EOH            ', & ! index 133 - 135
     'ETHLN          ','N2O5           ','ISNOHOO        ', & ! index 136 - 138
     'C2H6           ','MTPA           ','MTPO           ', & ! index 139 - 141
     'NPMN           ','IONO2          ','MOBAOO         ', & ! index 142 - 144
     'DIBOO          ','ISNOOB         ','IPMN           ', & ! index 145 - 147
     'LIMO           ','INPN           ','BrNO3          ', & ! index 148 - 150
     'MACRNO2        ','H              ','ROH            ', & ! index 151 - 153
     'MONITS         ','Cl2            ','I2             ', & ! index 154 - 156
     'ISOPNB         ','CH4            ','MVKOO          ', & ! index 157 - 159
     'GAOO           ','CH3CHOO        ','MVKN           ', & ! index 160 - 162
     'IEPOXOO        ','MGLYOO         ','GLYX           ', & ! index 163 - 165
     'MONITU         ','MGLOO          ','PRN1           ', & ! index 166 - 168
     'A3O2           ','CH2OO          ','PROPNN         ', & ! index 169 - 171
     'MAN2           ','ISNOOA         ','PO2            ', & ! index 172 - 174
     'B3O2           ','ISOPNDO2       ','MACROO         ', & ! index 175 - 177
     'R4N1           ','MAOPO2         ','H2O2           ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(65) :: SPC_NAMES_2 = (/ &
     'ISOP           ','MACRN          ','ATO2           ', & ! index 181 - 183
     'HCOOH          ','I              ','RCO3           ', & ! index 184 - 186
     'LIMO2          ','IO             ','OLND           ', & ! index 187 - 189
     'OLNN           ','KO2            ','HOBr           ', & ! index 190 - 192
     'PIO2           ','HC5OO          ','ISOPNBO2       ', & ! index 193 - 195
     'HNO3           ','ISOPND         ','HOCl           ', & ! index 196 - 198
     'NMAO3          ','ACTA           ','VRO2           ', & ! index 199 - 201
     'ISN1           ','GLYC           ','ClNO3          ', & ! index 202 - 204
     'MGLY           ','ACET           ','HC5            ', & ! index 205 - 207
     'RIO2           ','INO2           ','R4O2           ', & ! index 208 - 210
     'ETO2           ','R4N2           ','HAC            ', & ! index 211 - 213
     'MRO2           ','BrO            ','PRPE           ', & ! index 214 - 216
     'RCHO           ','MEK            ','MACR           ', & ! index 217 - 219
     'CH2O           ','ALD2           ','MVK            ', & ! index 220 - 222
     'MCO3           ','SO2            ','HCl            ', & ! index 223 - 225
     'HBr            ','ClO            ','NO             ', & ! index 226 - 228
     'Br             ','O1D            ','HO2            ', & ! index 229 - 231
     'NO3            ','O3             ','O              ', & ! index 232 - 234
     'MO2            ','OH             ','H2O            ', & ! index 235 - 237
     'NO2            ','CO             ','Cl             ', & ! index 238 - 240
     'H2             ','MOH            ','N2             ', & ! index 241 - 243
     'O2             ','RCOOH          ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(245) :: SPC_NAMES = (/&
    SPC_NAMES_0, SPC_NAMES_1, SPC_NAMES_2 /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=15), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '         LSHENA --> O2                                                                              ', & ! index 1
     '         LSHENB --> LSHENA + 1.2 LSHENC                                                             ', & ! index 2
     'LSHEND + LSHENC --> LSHENE + O2                                                                     ', & ! index 3
     'LSHENC + LSHENF --> LSHENB                                                                          ', & ! index 4
     '         LSHENF --> LSHENE + O2                                                                     ', & ! index 5
     '        NO + O3 --> NO2 + O2                                                                        ', & ! index 6
     '        O3 + OH --> LOx + HO2 + O2                                                                  ', & ! index 7
     '       HO2 + O3 --> LOx + OH + 2 O2                                                                 ', & ! index 8
     '       O3 + NO2 --> NO3 + O2                                                                        ', & ! index 9
     '       O3 + MO2 --> LOx + CH2O + HO2 + O2                                                           ', & ! index 10
     '           2 OH --> POx + O + H2O                                                                   ', & ! index 11
     '           2 OH --> H2O2                                                                            ', & ! index 12
     '       HO2 + OH --> H2O + O2                                                                        ', & ! index 13
     '      H2O2 + OH --> HO2 + H2O                                                                       ', & ! index 14
     '       NO + HO2 --> POx + OH + NO2                                                                  ', & ! index 15
     '          2 HO2 --> H2O2 + O2                                                                       ', & ! index 16
     '        OH + CO --> CO2 + LCO + HO2                                                                 ', & ! index 17
     '       CH4 + OH --> LCH4 + MO2 + H2O                                                                ', & ! index 18
     '       NO + MO2 --> POx + CH2O + HO2 + NO2                                                          ', & ! index 19
     '      HO2 + MO2 --> MP + O2                                                                         ', & ! index 20
     '          2 MO2 --> CH2O + MOH + O2                                                                 ', & ! index 21
     '          2 MO2 --> 2 CH2O + 2 HO2                                                                  ', & ! index 22
     '        MP + OH --> MO2 + H2O                                                                       ', & ! index 23
     '        MP + OH --> CH2O + OH + H2O                                                                 ', & ! index 24
     '     ATOOH + OH --> ATO2 + H2O                                                                      ', & ! index 25
     '     ATOOH + OH --> MGLY + OH + H2O                                                                 ', & ! index 26
     '      CH2O + OH --> PCO + HO2 + H2O + CO                                                            ', & ! index 27
     '       OH + NO2 --> HNO3                                                                            ', & ! index 28
     '      HNO3 + OH --> POx + NO3 + H2O                                                                 ', & ! index 29
     '        NO + OH --> HNO2                                                                            ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '      HNO2 + OH --> POx + H2O + NO2                                                                 ', & ! index 31
     '      HO2 + NO2 --> HNO4                                                                            ', & ! index 32
     '           HNO4 --> HO2 + NO2                                                                       ', & ! index 33
     '      HNO4 + OH --> H2O + NO2 + O2                                                                  ', & ! index 34
     '      HO2 + NO3 --> LOx + OH + NO2 + O2                                                             ', & ! index 35
     '       NO + NO3 --> 2 NO2                                                                           ', & ! index 36
     '       NO3 + OH --> LOx + HO2 + NO2                                                                 ', & ! index 37
     '      NO3 + NO2 --> N2O5                                                                            ', & ! index 38
     '           N2O5 --> NO3 + NO2                                                                       ', & ! index 39
     '     HCOOH + OH --> CO2 + HO2 + H2O                                                                 ', & ! index 40
     '       OH + MOH --> CH2O + HO2                                                                      ', & ! index 41
     '      NO3 + NO2 --> 2 LOx + NO + NO2 + O2                                                           ', & ! index 42
     '     CH2O + NO3 --> LOx + PCO + HNO3 + HO2 + CO                                                     ', & ! index 43
     '      ALD2 + OH --> 0.05 PCO + 0.05 CH2O + 0.95 MCO3 + 0.05 HO2 + H2O + 0.05 CO                     ', & ! index 44
     '     ALD2 + NO3 --> LOx + HNO3 + MCO3                                                               ', & ! index 45
     '     MCO3 + NO2 --> PAN                                                                             ', & ! index 46
     '            PAN --> MCO3 + NO2                                                                      ', & ! index 47
     '      MCO3 + NO --> CO2 + POx + MO2 + NO2                                                           ', & ! index 48
     '      C2H6 + OH --> ETO2 + H2O                                                                      ', & ! index 49
     '      ETO2 + NO --> POx + ALD2 + HO2 + NO2                                                          ', & ! index 50
     '      C3H8 + OH --> B3O2                                                                            ', & ! index 51
     '      C3H8 + OH --> A3O2                                                                            ', & ! index 52
     '      A3O2 + NO --> POx + RCHO + HO2 + NO2                                                          ', & ! index 53
     '       PO2 + NO --> POx + CH2O + ALD2 + HO2 + NO2                                                   ', & ! index 54
     '      ALK4 + OH --> R4O2                                                                            ', & ! index 55
     '      R4O2 + NO --> POx + 0.05 A3O2 + 0.18 B3O2 + 0.32 ACET + 0.32 ETO2 + 0.14 RCHO + 0.19 MEK + 0.3', & ! index 56
     '      R4O2 + NO --> POx + R4N2                                                                      ', & ! index 57
     '      R4N1 + NO --> POx + 0.57 RCHO + 0.57 CH2O + 0.86 ALD2 + 2 NO2                                 ', & ! index 58
     '      ATO2 + NO --> POx + CH2O + MCO3 + NO2                                                         ', & ! index 59
     '       KO2 + NO --> POx + 0.07 R4N2 + 0.93 ALD2 + 0.93 MCO3 + 0.93 NO2                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '      RIO2 + NO --> POx + 0.03 DIBOO + 0.081 ISOPNB + 0.009 ISOPND + 0.058 HC5 + 0.344 MACR + 0.82 C', & ! index 61
     '           RIO2 --> 0.5 HPALD + 0.5 DHPCARP                                                         ', & ! index 62
     '      VRO2 + NO --> POx + 0.12 MVKN + 0.53 GLYC + 0.35 MGLY + 0.35 CH2O + 0.53 MCO3 + 0.35 HO2 + 0.8', & ! index 63
     '      MRO2 + NO --> POx + 0.728 PCO + 0.15 MACRN + 0.122 MGLY + 0.728 HAC + 0.122 CH2O + 0.85 HO2 + ', & ! index 64
     '           MRO2 --> PCO + HAC + OH + CO                                                             ', & ! index 65
     '      MAN2 + NO --> POx + 0.5 PCO + 0.5 PROPNN + 0.5 MGLY + 0.5 CH2O + 0.5 OH + 1.5 NO2 + 0.5 CO    ', & ! index 66
     '      B3O2 + NO --> POx + ACET + HO2 + NO2                                                          ', & ! index 67
     '      INO2 + NO --> POx + 0.7 ISN1 + 0.23 HC5 + 0.035 MACR + 0.07 CH2O + 0.035 MVK + 0.8 HO2 + 1.3 N', & ! index 68
     '     INO2 + NO3 --> LOx + 0.7 ISN1 + 0.23 HC5 + 0.035 MACR + 0.07 CH2O + 0.035 MVK + 0.8 HO2 + 1.3 N', & ! index 69
     '     ISN1 + NO3 --> 1.4 LOx + 0.4 ISNOOB + 0.6 ISNOOA + 0.6 HNO3                                    ', & ! index 70
     '   ISNOOA + NO3 --> 0.04 ISN1OG + 1.04 LOx + PCO + 0.96 PROPNN + HO2 + NO2 + CO                     ', & ! index 71
     '    ISNOOA + NO --> 0.04 ISN1OG + 0.96 POx + PCO + 0.96 PROPNN + HO2 + NO2 + CO                     ', & ! index 72
     '   ISNOOA + NO2 --> 0.04 ISN1OG + 1.04 LOx + 0.96 IPMN                                              ', & ! index 73
     '   ISNOOA + HO2 --> 0.04 ISN1OG + 0.21 POx + 0.75 RP + 0.25 O3 + 0.96 NO2 + 0.25 RCOOH              ', & ! index 74
     '   ISNOOB + NO3 --> 0.04 ISN1OG + 0.06 LOx + GLYX + 0.94 PROPNN + 2 NO2                             ', & ! index 75
     '    ISNOOB + NO --> 0.04 ISN1OG + 1.78 POx + 0.94 GLYX + 0.9 PROPNN + 1.88 NO2                      ', & ! index 76
     '   ISNOOB + HO2 --> 0.04 ISN1OG + 0.04 LOx + 0.96 INPN                                              ', & ! index 77
     '   ISNOOB + MO2 --> 0.04 ISN1OG + 0.36 POx + 0.7 GLYX + 0.66 PROPNN + 0.75 CH2O + 0.5 HO2 + 0.7 NO2 ', & ! index 78
     '      ISN1 + O3 --> LOx + 0.7 GLYX + 0.3 PROPNN + 0.75 CH2O + 0.5 HO2 + 0.7 NO2 + 0.25 MOH          ', & ! index 79
     '      ISN1 + OH --> 0.655 ISNOHOO + 0.345 ISNOOA                                                    ', & ! index 80
     '   ISNOHOO + NO --> 0.04 ISN1OG + 0.106 LOx + 0.919 GLYX + 0.894 PROPNN + 0.934 HO2                 ', & ! index 81
     '  ISNOHOO + HO2 --> 0.04 ISN1OG + 0.04 LOx + 0.96 INPN                                              ', & ! index 82
     '  ISNOHOO + MO2 --> 0.04 ISN1OG + 0.34 LOx + 0.7 GLYX + 0.66 PROPNN + 0.75 CH2O + 1.2 HO2 + 0.25 MOH', & ! index 83
     '         2 INO2 --> 0.5 ISOPND + 1.2 ISN1 + 0.23 HC5 + 0.035 MACR + 0.07 CH2O + 0.035 MVK + 0.8 HO2 ', & ! index 84
     '      PRN1 + NO --> POx + CH2O + ALD2 + 2 NO2                                                       ', & ! index 85
     '     ALK4 + NO3 --> LOx + HNO3 + R4O2                                                               ', & ! index 86
     '      R4N2 + OH --> R4N1 + H2O                                                                      ', & ! index 87
     '      ACTA + OH --> CO2 + MO2 + H2O                                                                 ', & ! index 88
     '      RCHO + OH --> RCO3 + H2O                                                                      ', & ! index 89
     '     RCO3 + NO2 --> PPN                                                                             ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '            PPN --> RCO3 + NO2                                                                      ', & ! index 91
     '    IMAO3 + NO2 --> IPMN                                                                            ', & ! index 92
     '    NMAO3 + NO2 --> NPMN                                                                            ', & ! index 93
     '           IPMN --> IMAO3 + NO2                                                                     ', & ! index 94
     '           NPMN --> NMAO3 + NO2                                                                     ', & ! index 95
     '      RCO3 + NO --> POx + ETO2 + NO2                                                                ', & ! index 96
     '     NMAO3 + NO --> CO2 + POx + 0.5 PCO + 0.5 CH2O + 0.5 MCO3 + 0.5 MO2 + NO2 + 0.5 CO              ', & ! index 97
     '     RCHO + NO3 --> LOx + RCO3 + HNO3                                                               ', & ! index 98
     '      ACET + OH --> ATO2 + H2O                                                                      ', & ! index 99
     '     A3O2 + MO2 --> 0.25 ROH + 0.75 RCHO + 0.75 CH2O + HO2 + 0.25 MOH                               ', & ! index 100
     '      PO2 + MO2 --> 0.25 ROH + 0.16 HAC + 0.09 RCHO + 1.25 CH2O + 0.5 ALD2 + HO2 + 0.25 MOH         ', & ! index 101
     '     R4O2 + HO2 --> R4P                                                                             ', & ! index 102
     '     R4N1 + HO2 --> R4N2                                                                            ', & ! index 103
     '     ATO2 + HO2 --> 0.85 ATOOH + 0.15 CH2O + 0.15 MCO3 + 0.15 OH                                    ', & ! index 104
     '      KO2 + HO2 --> 0.85 ATOOH + 0.15 ALD2 + 0.15 MCO3 + 0.15 OH                                    ', & ! index 105
     '     RIO2 + HO2 --> 0.272 RIPB + 0.628 RIPA + 0.037 RIPD + 0.025 MACR + 0.063 CH2O + 0.038 MVK + 0.0', & ! index 106
     '     VRO2 + HO2 --> 0.1 VRP + 0.578 GLYC + 0.102 MGLY + 0.033 RCHO + 0.187 MEK + 0.102 CH2O + 0.578 ', & ! index 107
     '     MRO2 + HO2 --> MRP                                                                             ', & ! index 108
     '     MAN2 + HO2 --> 0.075 PCO + 0.85 MAOP + 0.075 PROPNN + 0.075 MGLY + 0.075 CH2O + 0.075 HO2 + 0.1', & ! index 109
     '     B3O2 + HO2 --> RB3P                                                                            ', & ! index 110
     '     INO2 + HO2 --> INPN                                                                            ', & ! index 111
     '     PRN1 + HO2 --> PRPN                                                                            ', & ! index 112
     '       MEK + OH --> KO2 + H2O                                                                       ', & ! index 113
     '     ETO2 + MO2 --> 0.25 EOH + 0.75 CH2O + 0.75 ALD2 + HO2 + 0.25 MOH                               ', & ! index 114
     '      MEK + NO3 --> LOx + KO2 + HNO3                                                                ', & ! index 115
     '     R4O2 + MO2 --> 0.25 ROH + 0.03 A3O2 + 0.09 B3O2 + 0.16 ACET + 0.16 ETO2 + 0.07 RCHO + 0.35 MEK ', & ! index 116
     '     R4N1 + MO2 --> 0.25 ROH + 0.15 R4O2 + 0.54 RCHO + 0.95 CH2O + 0.38 ALD2 + 0.5 HO2 + NO2 + 0.25 ', & ! index 117
     '     ATO2 + MO2 --> 0.5 MGLY + 0.2 HAC + 0.5 CH2O + 0.3 MCO3 + 0.3 HO2 + 0.5 MOH                    ', & ! index 118
     '      KO2 + MO2 --> 0.25 ROH + 0.25 MEK + 0.75 CH2O + 0.5 ALD2 + 0.5 MCO3 + 0.5 HO2 + 0.25 MOH      ', & ! index 119
     '     RIO2 + MO2 --> 0.24 ROH + 0.3 HC5 + 0.18 MACR + 1.22 CH2O + 0.28 MVK + 1.1 HO2 + 0.24 MOH      ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_4 = (/ &
     '         2 RIO2 --> 0.29 PCO + 0.09 DIBOO + 1.11 HC5 + 0.29 MACR + 0.75 CH2O + 0.45 MVK + 0.91 HO2 +', & ! index 121
     '    HC5OO + MO2 --> 0.33 PCO + 0.25 ROH + 0.13 GLYC + 0.29 MGLY + 0.18 HAC + 0.25 MEK + 0.95 CH2O + ', & ! index 122
     '     VRO2 + MO2 --> 0.25 ROH + 0.36 GLYC + 0.14 MGLY + 0.25 MEK + 0.89 CH2O + 0.36 MCO3 + 0.64 HO2 +', & ! index 123
     '     MRO2 + MO2 --> 0.595 PCO + 0.15 ROH + 0.255 MGLY + 0.595 HAC + 1.255 CH2O + 1.7 HO2 + 0.595 CO ', & ! index 124
     '     MAN2 + MO2 --> 0.375 PCO + 0.375 PROPNN + 0.375 MGLY + 0.25 R4N2 + 0.625 CH2O + 0.375 HO2 + 0.3', & ! index 125
     '     B3O2 + MO2 --> 0.25 ROH + 0.75 ACET + 0.75 CH2O + HO2 + 0.25 MOH                               ', & ! index 126
     '     INO2 + MO2 --> 0.25 ISOPND + 0.6 ISN1 + 0.115 HC5 + 0.018 MACR + 0.785 CH2O + 0.018 MVK + 0.9 H', & ! index 127
     '     PRN1 + MO2 --> 0.25 ROH + 0.25 RCHO + 1.25 CH2O + 0.5 ALD2 + 0.5 HO2 + NO2 + 0.25 MOH          ', & ! index 128
     '       EOH + OH --> ALD2 + HO2                                                                      ', & ! index 129
     '       ROH + OH --> RCHO + HO2                                                                      ', & ! index 130
     '         2 ETO2 --> 2 ALD2 + 2 HO2                                                                  ', & ! index 131
     '         2 ETO2 --> EOH + ALD2                                                                      ', & ! index 132
     '     ETO2 + HO2 --> ETP                                                                             ', & ! index 133
     '     A3O2 + HO2 --> RA3P                                                                            ', & ! index 134
     '      PO2 + HO2 --> PP                                                                              ', & ! index 135
     '     MCO3 + HO2 --> 0.15 POx + 0.41 MAP + 0.15 ACTA + 0.15 O3 + 0.44 MO2 + 0.44 OH                  ', & ! index 136
     '     RCO3 + HO2 --> 0.15 POx + 0.41 RP + 0.44 ETO2 + 0.15 O3 + 0.44 OH + 0.15 RCOOH                 ', & ! index 137
     '    NMAO3 + HO2 --> 0.15 POx + 0.39 PCO + 0.41 MAOP + 0.59 CH2O + 0.15 O3 + 0.39 MO2 + 0.44 OH + 0.3', & ! index 138
     '      PRPE + OH --> PO2                                                                             ', & ! index 139
     '      PRPE + O3 --> LOx + 0.56 PCO + 0.1 CH4 + 0.12 CH3CHOO + 0.12 CH2OO + 0.5 CH2O + 0.5 ALD2 + 0.2', & ! index 140
     '      NPMN + OH --> PCO + HAC + NO2 + CO                                                            ', & ! index 141
     '      IPMN + OH --> 0.781 IMAE + 0.81 POx + 0.03 PCO + 0.19 PAN + 0.03 HAC + 0.19 CH2O + 0.19 HO2 + ', & ! index 142
     '      NPMN + O3 --> CH2O + MCO3 + NO3                                                               ', & ! index 143
     '      IMAE + OH --> OH                                                                              ', & ! index 144
     '      GLYC + OH --> 0.361 CO2 + 0.505 PCO + 0.134 GLYX + 0.134 HCOOH + 0.732 CH2O + 0.773 HO2 + 0.22', & ! index 145
     '      GLYC + OH --> PCO + HCOOH + OH + CO                                                           ', & ! index 146
     '     PRPE + NO3 --> LOx + PRN1                                                                      ', & ! index 147
     '      GLYX + OH --> 2 PCO + HO2 + 2 CO                                                              ', & ! index 148
     '      MGLY + OH --> PCO + MCO3 + CO                                                                 ', & ! index 149
     '     GLYX + NO3 --> LOx + 2 PCO + HNO3 + HO2 + 2 CO                                                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_5 = (/ &
     '     MGLY + NO3 --> LOx + PCO + HNO3 + MCO3 + CO                                                    ', & ! index 151
     '      ISOP + OH --> LISOPOH + RIO2                                                                  ', & ! index 152
     '       MVK + OH --> VRO2                                                                            ', & ! index 153
     '      MACR + OH --> 0.53 IMAO3 + 0.47 MRO2                                                          ', & ! index 154
     '       HAC + OH --> MGLY + HO2                                                                      ', & ! index 155
     '       HAC + OH --> 0.5 CO2 + 0.5 PCO + 0.5 HCOOH + 0.5 ACTA + 0.5 MO2 + OH + 0.5 CO                ', & ! index 156
     '    A3O2 + MCO3 --> RCHO + HO2 + MO2                                                                ', & ! index 157
     '     PO2 + MCO3 --> CH2O + ALD2 + HO2 + MO2                                                         ', & ! index 158
     '    A3O2 + MCO3 --> ACTA + RCHO                                                                     ', & ! index 159
     '     PO2 + MCO3 --> ACTA + 0.65 HAC + 0.35 RCHO                                                     ', & ! index 160
     '      ISOP + O3 --> LOx + 0.495 PCO + 0.044 MVKOO + 0.11 CH2OO + 0.044 MACROO + 0.054 VRO2 + 0.102 P', & ! index 161
     '       MVK + O3 --> LOx + 0.56 PCO + 0.12 MGLOO + 0.12 CH2OO + 0.5 MGLY + 0.6 CH2O + 0.1 ALD2 + 0.28', & ! index 162
     '      MACR + O3 --> LOx + 0.625 PCO + 0.022 MGLYOO + 0.326 CH2OO + 0.88 MGLY + 0.12 CH2O + 0.098 MCO', & ! index 163
     '     ISOP + NO3 --> LISOPNO3 + LOx + INO2                                                           ', & ! index 164
     '     MACR + NO3 --> LOx + MAN2                                                                      ', & ! index 165
     '     MACR + NO3 --> 1.5 LOx + 0.5 PCO + 0.5 IMAO3 + 0.5 MAOP + 0.5 HNO3 + 0.5 MRO2 + 0.5 HO2 + 0.5 C', & ! index 166
     '     RCO3 + MO2 --> ETO2 + CH2O + HO2                                                               ', & ! index 167
     '    NMAO3 + MO2 --> 2 CH2O + MCO3 + HO2                                                             ', & ! index 168
     '     RCO3 + MO2 --> CH2O + RCOOH                                                                    ', & ! index 169
     '    NMAO3 + MO2 --> CH2O + RCOOH                                                                    ', & ! index 170
     '      INPN + OH --> MEK + OH + NO2                                                                  ', & ! index 171
     '      INPN + OH --> 0.36 INO2 + 0.64 R4N2 + 0.64 OH                                                 ', & ! index 172
     '      PRPN + OH --> 0.209 PRN1 + 0.791 PROPNN + 0.791 OH                                            ', & ! index 173
     '       ETP + OH --> 0.36 ETO2 + 0.64 ALD2 + 0.64 OH                                                 ', & ! index 174
     '      RA3P + OH --> 0.36 A3O2 + 0.64 RCHO + 0.64 OH                                                 ', & ! index 175
     '      RB3P + OH --> 0.209 B3O2 + 0.791 ACET + 0.791 OH                                              ', & ! index 176
     '       R4P + OH --> 0.209 R4O2 + 0.791 RCHO + 0.791 OH                                              ', & ! index 177
     '        RP + OH --> RCO3                                                                            ', & ! index 178
     '        PP + OH --> 0.209 PO2 + 0.791 HAC + 0.791 OH                                                ', & ! index 179
     '      RIPA + OH --> 0.007 LVOC + 0.243 HC5 + 0.75 RIO2 + 0.125 OH + 0.125 H2O                       ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_6 = (/ &
     '      RIPB + OH --> 0.007 LVOC + 0.513 HC5 + 0.48 RIO2 + 0.26 OH + 0.26 H2O                         ', & ! index 181
     '      RIPD + OH --> 0.007 LVOC + 0.743 HC5 + 0.25 RIO2 + 0.375 OH + 0.375 H2O                       ', & ! index 182
     '      RIPA + OH --> 0.007 LVOC + 0.578 IEPOXA + 0.272 IEPOXB + 0.143 HC5OO + 0.85 OH                ', & ! index 183
     '      RIPB + OH --> 0.68 IEPOXA + 0.32 IEPOXB + OH                                                  ', & ! index 184
     '      RIPD + OH --> 0.007 LVOC + 0.5 IEPOXD + 0.493 HC5OO + 0.5 OH                                  ', & ! index 185
     '      LVOC + OH --> OH                                                                              ', & ! index 186
     '    IEPOXA + OH --> IEPOXOO                                                                         ', & ! index 187
     '    IEPOXB + OH --> IEPOXOO                                                                         ', & ! index 188
     '    IEPOXD + OH --> IEPOXOO                                                                         ', & ! index 189
     '  IEPOXOO + HO2 --> 1.172 CO2 + 0.6 PCO + 0.44 HC187 + 0.085 GLYX + 0.278 HCOOH + 0.025 GLYC + 0.085', & ! index 190
     '   IEPOXOO + NO --> 0.858 CO2 + POx + 0.678 PCO + 0.473 HC187 + 0.088 GLYX + 0.142 HCOOH + 0.088 GLY', & ! index 191
     '       IAP + OH --> 0.654 DHMOB + 0.346 HC5OO + 0.654 OH                                            ', & ! index 192
     '       VRP + OH --> 0.209 VRO2 + 0.791 MEK + 0.791 OH                                               ', & ! index 193
     '       MRP + OH --> MRO2                                                                            ', & ! index 194
     '       MRP + OH --> CO2 + HAC + OH                                                                  ', & ! index 195
     '      MAOP + OH --> NMAO3                                                                           ', & ! index 196
     '      MAOP + OH --> MAOPO2                                                                          ', & ! index 197
     '  MAOPO2 + MCO3 --> 2 CO2 + HAC + MO2 + OH                                                          ', & ! index 198
     '  MAOPO2 + MCO3 --> ACTA + MEK                                                                      ', & ! index 199
     '   MAOPO2 + MO2 --> 0.7 CO2 + 0.3 ROH + 0.7 HAC + CH2O + 0.7 HO2 + 0.7 OH                           ', & ! index 200
     '       2 MAOPO2 --> 2 CO2 + 2 HAC + 2 OH                                                            ', & ! index 201
     '   MAOPO2 + HO2 --> CO2 + HAC + 2 OH                                                                ', & ! index 202
     '    MAOPO2 + NO --> CO2 + POx + HAC + OH + NO2                                                      ', & ! index 203
     '    MAOPO2 + NO --> POx + HNO3                                                                      ', & ! index 204
     '       MAP + OH --> MCO3                                                                            ', & ! index 205
     '     C2H6 + NO3 --> LOx + HNO3 + ETO2                                                               ', & ! index 206
     '       HC5 + O3 --> LOx + 0.89 PCO + 0.055 GAOO + 0.055 MGLYOO + 0.5 GLYC + 0.5 MGLY + 0.445 CH2O + ', & ! index 207
     '         2 MCO3 --> 2 MO2                                                                           ', & ! index 208
     '     MCO3 + MO2 --> CH2O + HO2 + MO2                                                                ', & ! index 209
     '     MCO3 + MO2 --> ACTA + CH2O                                                                     ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_7 = (/ &
     '    R4O2 + MCO3 --> 0.05 A3O2 + 0.18 B3O2 + 0.32 ACET + 0.32 ETO2 + 0.13 RCHO + 0.19 MEK + 0.32 ALD2', & ! index 211
     '    ATO2 + MCO3 --> CH2O + MCO3 + MO2                                                               ', & ! index 212
     '     KO2 + MCO3 --> ALD2 + MCO3 + MO2                                                               ', & ! index 213
     '    RIO2 + MCO3 --> CO2 + 0.113 DIBOO + 0.14 HC5 + 0.294 MACR + 0.747 CH2O + 0.453 MVK + 0.887 HO2 +', & ! index 214
     '   HC5OO + MCO3 --> 0.09 PCO + 0.17 MOBA + 0.29 DHMOB + 0.216 GLYX + 0.234 GLYC + 0.234 MGLY + 0.216', & ! index 215
     '    VRO2 + MCO3 --> 0.6 GLYC + 0.4 MGLY + 0.4 CH2O + 0.6 MCO3 + 0.4 HO2 + MO2                       ', & ! index 216
     '    MRO2 + MCO3 --> 0.857 PCO + 0.143 MGLY + 0.857 HAC + 0.143 CH2O + 0.85 HO2 + MO2 + 0.857 CO     ', & ! index 217
     '    B3O2 + MCO3 --> ACET + HO2 + MO2                                                                ', & ! index 218
     '    R4N1 + MCO3 --> 0.3 R4O2 + 0.57 RCHO + 0.39 CH2O + 0.75 ALD2 + MO2 + NO2                        ', & ! index 219
     '    MAN2 + MCO3 --> CO2 + 0.5 PCO + 0.5 PROPNN + 0.5 MGLY + 0.5 CH2O + 0.5 HO2 + MO2 + 0.5 NO2 + 0.5', & ! index 220
     '    INO2 + MCO3 --> 0.7 ISN1 + 0.23 HC5 + 0.035 MACR + 0.07 CH2O + 0.035 MVK + 0.8 HO2 + MO2 + 0.3 N', & ! index 221
     '    PRN1 + MCO3 --> CH2O + ALD2 + MO2 + NO2                                                         ', & ! index 222
     '    R4O2 + MCO3 --> ACTA + MEK                                                                      ', & ! index 223
     '    ATO2 + MCO3 --> ACTA + MGLY                                                                     ', & ! index 224
     '     KO2 + MCO3 --> ACTA + MEK                                                                      ', & ! index 225
     '    RIO2 + MCO3 --> ACTA + MEK                                                                      ', & ! index 226
     '   HC5OO + MCO3 --> ACTA + MEK                                                                      ', & ! index 227
     '    VRO2 + MCO3 --> ACTA + MEK                                                                      ', & ! index 228
     '    MRO2 + MCO3 --> ACTA + MEK                                                                      ', & ! index 229
     '    R4N1 + MCO3 --> ACTA + RCHO + NO2                                                               ', & ! index 230
     '    MAN2 + MCO3 --> ACTA + RCHO + NO2                                                               ', & ! index 231
     '    INO2 + MCO3 --> ACTA + RCHO + NO2                                                               ', & ! index 232
     '    PRN1 + MCO3 --> ACTA + RCHO + NO2                                                               ', & ! index 233
     '    B3O2 + MCO3 --> ACTA + ACET                                                                     ', & ! index 234
     '    ETO2 + MCO3 --> ALD2 + HO2 + MO2                                                                ', & ! index 235
     '    ETO2 + MCO3 --> ACTA + ALD2                                                                     ', & ! index 236
     '    RCO3 + MCO3 --> ETO2 + MO2                                                                      ', & ! index 237
     '   NMAO3 + MCO3 --> CH2O + MCO3 + MO2                                                               ', & ! index 238
     '          2 NO3 --> 2 LOx + 2 NO2 + O2                                                              ', & ! index 239
     '      MO2 + NO2 --> MPN                                                                             ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_8 = (/ &
     '            MPN --> MO2 + NO2                                                                       ', & ! index 241
     '    ISOPNB + O3 --> 0.36 CO2 + 0.64 LOx + 0.21 PCO + 0.21 MVKN + 0.42 PROPNN + 0.32 MACRN + 0.16 HCO', & ! index 242
     '    ISOPND + O3 --> 0.63 CO2 + LOx + 0.09 EOH + 0.26 ETHLN + 0.06 GLYX + 0.38 PROPNN + 0.3 HNO3 + 0.', & ! index 243
     '       DMS + OH --> CH2O + SO2 + MO2                                                                ', & ! index 244
     '       DMS + OH --> 0.25 MSA + 0.75 SO2 + MO2                                                       ', & ! index 245
     '      DMS + NO3 --> LOx + HNO3 + CH2O + SO2 + MO2                                                   ', & ! index 246
     '       SO2 + OH --> PSO4 + SO4 + HO2                                                                ', & ! index 247
     '        Br + O3 --> BrO + O2                                                                        ', & ! index 248
     '      BrO + HO2 --> HOBr + O2                                                                       ', & ! index 249
     '       Br + HO2 --> HBr + O2                                                                        ', & ! index 250
     '       HBr + OH --> Br + H2O                                                                        ', & ! index 251
     '          2 BrO --> 2 LOx + 2 Br + O2                                                               ', & ! index 252
     '          2 BrO --> 2 LOx + Br2 + O2                                                                ', & ! index 253
     '       BrO + NO --> Br + NO2                                                                        ', & ! index 254
     '     BrNO3 + Br --> Br2 + NO3                                                                       ', & ! index 255
     '       Br2 + OH --> POx + HOBr + Br                                                                 ', & ! index 256
     '       HOBr + O --> LOx + BrO + OH                                                                  ', & ! index 257
     '        HBr + O --> LOx + Br + OH                                                                   ', & ! index 258
     '       BrO + OH --> LOx + Br + HO2                                                                  ', & ! index 259
     '       Br + NO3 --> BrO + NO2                                                                       ', & ! index 260
     '      CH2O + Br --> PCO + HBr + HO2 + CO                                                            ', & ! index 261
     '      ALD2 + Br --> MCO3 + HBr                                                                      ', & ! index 262
     '      ACET + Br --> ATO2 + HBr                                                                      ', & ! index 263
     '      C2H6 + Br --> ETO2 + HBr                                                                      ', & ! index 264
     '      C3H8 + Br --> A3O2 + HBr                                                                      ', & ! index 265
     '       Br + NO2 --> BrNO2                                                                           ', & ! index 266
     '      BrO + NO2 --> BrNO3                                                                           ', & ! index 267
     '     CHBr3 + OH --> 3 Br                                                                            ', & ! index 268
     '    CH2Br2 + OH --> 2 Br                                                                            ', & ! index 269
     '     CH3Br + OH --> Br + HO2 + H2O                                                                  ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_9 = (/ &
     '      O1D + H2O --> LOx + 2 OH                                                                      ', & ! index 271
     '       O1D + N2 --> O + N2                                                                          ', & ! index 272
     '       O1D + O2 --> O + O2                                                                          ', & ! index 273
     '       O1D + H2 --> LOx + H + OH                                                                    ', & ! index 274
     '      N2O + O1D --> LOx + N2 + O2                                                                   ', & ! index 275
     '      N2O + O1D --> LOx + 2 NO                                                                      ', & ! index 276
     '      CH4 + O1D --> LOx + LCH4 + MO2 + OH                                                           ', & ! index 277
     '      CH4 + O1D --> LOx + LCH4 + CH2O + H2                                                          ', & ! index 278
     '      CH4 + O1D --> LOx + LCH4 + H + CH2O + HO2                                                     ', & ! index 279
     '         O + O2 --> O3                                                                              ', & ! index 280
     '         O3 + O --> 2 LOx + 2 O2                                                                    ', & ! index 281
     '        OH + H2 --> H + H2O                                                                         ', & ! index 282
     '         O + OH --> LOx + H + O2                                                                    ', & ! index 283
     '        HO2 + O --> LOx + OH + O2                                                                   ', & ! index 284
     '       O1D + O3 --> 2 LOx + 2 O2                                                                    ', & ! index 285
     '       O1D + O3 --> 2 O + O2                                                                        ', & ! index 286
     '        OCS + O --> LOx + PCO + SO2 + CO                                                            ', & ! index 287
     '       OCS + OH --> CO2 + SO2                                                                       ', & ! index 288
     '        O + NO2 --> 2 LOx + NO + O2                                                                 ', & ! index 289
     '        NO3 + O --> 2 LOx + NO2 + O2                                                                ', & ! index 290
     '         NO + O --> NO2                                                                             ', & ! index 291
     '        O + NO2 --> NO3                                                                             ', & ! index 292
     '       H2O2 + O --> LOx + HO2 + OH                                                                  ', & ! index 293
     '         H + O2 --> HO2                                                                             ', & ! index 294
     '         H + O3 --> LOx + OH + O2                                                                   ', & ! index 295
     '        H + HO2 --> 2 OH                                                                            ', & ! index 296
     '        H + HO2 --> POx + O + H2O                                                                   ', & ! index 297
     '        H + HO2 --> H2 + O2                                                                         ', & ! index 298
     '         N + O2 --> POx + NO + O                                                                    ', & ! index 299
     '         N + NO --> POx + O + N2                                                                    ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_10 = (/ &
     '        N + NO2 --> N2O + O                                                                         ', & ! index 301
     '        BrO + O --> 2 LOx + Br + O2                                                                 ', & ! index 302
     '       CH2O + O --> LOx + PCO + HO2 + OH + CO                                                       ', & ! index 303
     '      HCl + O1D --> 0.67 LOx + 0.24 H + 0.09 HCl + 0.24 ClO + 0.09 O + 0.67 OH + 0.67 Cl            ', & ! index 304
     '      HBr + O1D --> 0.65 LOx + 0.15 H + 0.15 BrO + 0.2 HBr + 0.65 Br + 0.2 O + 0.65 OH              ', & ! index 305
     '      Cl2 + O1D --> 0.25 Cl2 + 0.75 ClO + 0.25 O + 0.75 Cl                                          ', & ! index 306
     '     CCl4 + O1D --> 0.14 CCl4 + 0.86 ClO + 0.14 O + 2.58 Cl                                         ', & ! index 307
     '    CH3Br + O1D --> 0.56 LOx + 0.44 BrO + 0.56 Br + MO2                                             ', & ! index 308
     '   CH2Br2 + O1D --> 0.05 CH2Br2 + 0.95 BrO + 0.95 Br + 0.05 O                                       ', & ! index 309
     '    CHBr3 + O1D --> 0.32 CHBr3 + 0.68 BrO + 1.36 Br + 0.32 O                                        ', & ! index 310
     '   HCFC22 + O1D --> 0.17 LOx + 0.28 HCFC22 + 0.55 ClO + 0.28 O + 0.17 Cl                            ', & ! index 311
     '    CFC11 + O1D --> 0.12 CFC11 + 0.88 ClO + 0.12 O + 1.76 Cl                                        ', & ! index 312
     '    CFC12 + O1D --> 0.14 CFC12 + 0.86 ClO + 0.14 O + 1.72 Cl                                        ', & ! index 313
     '    H1211 + O1D --> 0.36 H1211 + 0.31 BrO + 0.33 ClO + 0.33 Br + 0.36 O + 0.31 Cl                   ', & ! index 314
     '    H1301 + O1D --> 0.59 H1301 + 0.41 BrO + 0.59 O                                                  ', & ! index 315
     ' HCFC141b + O1D --> 0.31 HCFC141b + 0.69 ClO + 0.31 O + 0.69 Cl                                     ', & ! index 316
     ' HCFC142b + O1D --> 0.26 HCFC142b + 0.74 ClO + 0.26 O                                               ', & ! index 317
     '  HCFC123 + O1D --> 0.21 HCFC123 + 0.79 ClO + 0.21 O + 0.79 Cl                                      ', & ! index 318
     '   CFC113 + O1D --> 0.25 CFC113 + 0.75 ClO + 0.25 O + 1.5 Cl                                        ', & ! index 319
     '   CFC114 + O1D --> 0.25 CFC114 + 0.75 ClO + 0.25 O + 0.75 Cl                                       ', & ! index 320
     '   CFC115 + O1D --> 0.7 CFC115 + 0.3 ClO + 0.7 O                                                    ', & ! index 321
     '    H2402 + O1D --> 0.25 H2402 + 0.75 BrO + 0.75 Br + 0.25 O                                        ', & ! index 322
     '       Cl2 + OH --> POx + HOCl + Cl                                                                 ', & ! index 323
     '      ClO + MO2 --> LOx + ClOO + CH2O + HO2                                                         ', & ! index 324
     '       ClO + OH --> LOx + HO2 + Cl                                                                  ', & ! index 325
     '       ClO + OH --> LOx + HCl + O2                                                                  ', & ! index 326
     '      OClO + OH --> LOx + HOCl + O2                                                                 ', & ! index 327
     '     Cl2O2 + OH --> LOx + ClOO + HOCl                                                               ', & ! index 328
     '       HCl + OH --> H2O + Cl                                                                        ', & ! index 329
     '      HOCl + OH --> ClO + H2O                                                                       ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_11 = (/ &
     '     ClNO2 + OH --> POx + HOCl + NO2                                                                ', & ! index 331
     '     ClNO3 + OH --> POx + HOCl + NO3                                                                ', & ! index 332
     '     CH3Cl + OH --> HO2 + H2O + Cl                                                                  ', & ! index 333
     '    CH2Cl2 + OH --> HO2 + 2 Cl                                                                      ', & ! index 334
     '     CHCl3 + OH --> HO2 + 3 Cl                                                                      ', & ! index 335
     '   CH3CCl3 + OH --> H2O + 3 Cl                                                                      ', & ! index 336
     '    HCFC22 + OH --> H2O + Cl                                                                        ', & ! index 337
     '  HCFC141b + OH --> H2O + 2 Cl                                                                      ', & ! index 338
     '  HCFC142b + OH --> H2O + Cl                                                                        ', & ! index 339
     '   HCFC123 + OH --> H2O + 2 Cl                                                                      ', & ! index 340
     '       CH4 + Cl --> LCH4 + HCl + MO2                                                                ', & ! index 341
     '      CH2O + Cl --> PCO + HCl + HO2 + CO                                                            ', & ! index 342
     '        O3 + Cl --> ClO + O2                                                                        ', & ! index 343
     '        Cl + H2 --> H + HCl                                                                         ', & ! index 344
     '      H2O2 + Cl --> HCl + HO2                                                                       ', & ! index 345
     '       HO2 + Cl --> HCl + O2                                                                        ', & ! index 346
     '       HO2 + Cl --> POx + ClO + OH                                                                  ', & ! index 347
     '        ClO + O --> 2 LOx + Cl + O2                                                                 ', & ! index 348
     '      ClO + HO2 --> HOCl + O2                                                                       ', & ! index 349
     '       ClO + NO --> NO2 + Cl                                                                        ', & ! index 350
     '      ClO + NO2 --> ClNO3                                                                           ', & ! index 351
     '          2 ClO --> 2 LOx + Cl2 + O2                                                                ', & ! index 352
     '          2 ClO --> 2 LOx + ClOO + Cl                                                               ', & ! index 353
     '          2 ClO --> OClO + Cl                                                                       ', & ! index 354
     '        Cl + O2 --> ClOO                                                                            ', & ! index 355
     '           ClOO --> Cl + O2                                                                         ', & ! index 356
     '          2 ClO --> Cl2O2                                                                           ', & ! index 357
     '          Cl2O2 --> 2 ClO                                                                           ', & ! index 358
     '      ClOO + Cl --> Cl2 + O2                                                                        ', & ! index 359
     '      ClOO + Cl --> 2 POx + 2 ClO                                                                   ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_12 = (/ &
     '      BrO + ClO --> OClO + Br                                                                       ', & ! index 361
     '      BrO + ClO --> 2 LOx + ClOO + Br                                                               ', & ! index 362
     '      BrO + ClO --> 2 LOx + BrCl + O2                                                               ', & ! index 363
     '      ClNO3 + O --> ClO + NO3                                                                       ', & ! index 364
     '     ClNO3 + Cl --> Cl2 + NO3                                                                       ', & ! index 365
     '     CH3Cl + Cl --> PCO + 2 HCl + HO2 + CO                                                          ', & ! index 366
     '    CH2Cl2 + Cl --> PCO + HCl + HO2 + CO + 2 Cl                                                     ', & ! index 367
     '     CHCl3 + Cl --> PCO + HCl + HO2 + CO + 3 Cl                                                     ', & ! index 368
     '     HCOOH + Cl --> CO2 + HCl + H2O                                                                 ', & ! index 369
     '       MO2 + Cl --> POx + CH2O + ClO + HO2                                                          ', & ! index 370
     '        MP + Cl --> HCl + MO2                                                                       ', & ! index 371
     '      C2H6 + Cl --> ETO2 + HCl                                                                      ', & ! index 372
     '      ETO2 + Cl --> POx + ALD2 + ClO + HO2                                                          ', & ! index 373
     '       Cl + MOH --> CH2O + HCl + HO2                                                                ', & ! index 374
     '       EOH + Cl --> ALD2 + HCl                                                                      ', & ! index 375
     '      ACTA + Cl --> CO2 + HCl + MO2                                                                 ', & ! index 376
     '      C3H8 + Cl --> B3O2 + HCl                                                                      ', & ! index 377
     '      C3H8 + Cl --> A3O2 + HCl                                                                      ', & ! index 378
     '      ACET + Cl --> ATO2 + HCl                                                                      ', & ! index 379
     '      ISOP + Cl --> RIO2 + HCl                                                                      ', & ! index 380
     '      ALK4 + Cl --> R4O2 + HCl                                                                      ', & ! index 381
     '      PRPE + Cl --> PO2 + HCl                                                                       ', & ! index 382
     '      PRPE + Br --> PO2 + HBr                                                                       ', & ! index 383
     '         I + NO --> INO                                                                             ', & ! index 384
     '          2 INO --> I2 + 2 NO                                                                       ', & ! index 385
     '        I + NO2 --> IONO                                                                            ', & ! index 386
     '           IONO --> I + NO2                                                                         ', & ! index 387
     '         2 IONO --> I2 + 2 NO2                                                                      ', & ! index 388
     '       I2 + NO3 --> IONO2 + I                                                                       ', & ! index 389
     '       IO + NO2 --> IONO2                                                                           ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_13 = (/ &
     '          IONO2 --> IO + NO2                                                                        ', & ! index 391
     '      IONO2 + I --> I2 + NO3                                                                        ', & ! index 392
     '        I + BrO --> IO + Br                                                                         ', & ! index 393
     '       IO + BrO --> 2 LOx + I + Br + O2                                                             ', & ! index 394
     '       IO + BrO --> OIO + Br                                                                        ', & ! index 395
     '       OIO + IO --> I2O3                                                                            ', & ! index 396
     '          2 OIO --> I2O4                                                                            ', & ! index 397
     '           I2O4 --> 2 OIO                                                                           ', & ! index 398
     '       OIO + NO --> IO + NO2                                                                        ', & ! index 399
     '       IO + ClO --> OClO + I                                                                        ', & ! index 400
     '       IO + ClO --> 2 LOx + I + Cl + O2                                                             ', & ! index 401
     '       IO + ClO --> 2 LOx + ICl + O2                                                                ', & ! index 402
     '         I + O3 --> IO + O2                                                                         ', & ! index 403
     '        I + HO2 --> HI + O2                                                                         ', & ! index 404
     '        I2 + OH --> POx + HOI + I                                                                   ', & ! index 405
     '        HI + OH --> I + H2O                                                                         ', & ! index 406
     '       HOI + OH --> IO + H2O                                                                        ', & ! index 407
     '       IO + HO2 --> HOI + O2                                                                        ', & ! index 408
     '        IO + NO --> I + NO2                                                                         ', & ! index 409
     '           2 IO --> OIO + I                                                                         ', & ! index 410
     '           2 IO --> I2O2                                                                            ', & ! index 411
     '           I2O2 --> 2 IO                                                                            ', & ! index 412
     '           I2O2 --> OIO + I                                                                         ', & ! index 413
     '      CH3I + OH --> I + MO2 + H2O                                                                   ', & ! index 414
     '       HC5 + OH --> HC5OO                                                                           ', & ! index 415
     '     HC5OO + NO --> POx + 0.09 PCO + 0.17 MOBA + 0.29 DHMOB + 0.216 GLYX + 0.234 GLYC + 0.234 MGLY +', & ! index 416
     '     HC5OO + NO --> POx + HNO3                                                                      ', & ! index 417
     '    HC5OO + HO2 --> 0.1 IAP + 0.9 GLYC + 0.9 MGLY + 0.9 HO2 + 0.9 OH                                ', & ! index 418
     '    ISOPND + OH --> 0.9 LOx + 0.1 IEPOXD + 0.9 ISOPNDO2 + 0.1 NO2                                   ', & ! index 419
     '    ISOPNB + OH --> 0.9 LOx + 0.067 IEPOXA + 0.033 IEPOXB + 0.9 ISOPNBO2 + 0.1 NO2                  ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_14 = (/ &
     '  ISOPNDO2 + NO --> 1.394 POx + 0.27 DHDN + 0.21 ETHLN + 0.075 MVKN + 0.3 PROPNN + 0.057 ISOPNDO2 + ', & ! index 421
     ' ISOPNDO2 + HO2 --> POx + 0.5 ISNP + 0.2 ETHLN + 0.06 MVKN + 0.23 PROPNN + 0.01 MACRN + 0.23 GLYC + ', & ! index 422
     '  ISOPNBO2 + NO --> 1.58 POx + 0.21 DHDN + 0.26 MVKN + 0.44 MACRN + 0.09 GLYC + 0.09 HAC + 0.7 CH2O ', & ! index 423
     ' ISOPNBO2 + HO2 --> 1.01 POx + 0.51 ISNP + 0.16 MVKN + 0.28 MACRN + 0.06 GLYC + 0.06 HAC + 0.44 CH2O', & ! index 424
     '      ISNP + OH --> 0.388 LOx + 0.193 ISOPNDO2 + 0.612 R4N1 + 0.193 ISOPNBO2 + 0.612 OH             ', & ! index 425
     '      MVKN + OH --> 0.35 PYAC + POx + 0.65 HCOOH + 0.65 MGLY + 0.35 CH2O + NO3                      ', & ! index 426
     '     MACRN + OH --> MACRNO2                                                                         ', & ! index 427
     '   MACRNO2 + NO --> 0.93 CO2 + 1.15 POx + 0.07 HCOOH + 0.08 ACTA + 0.07 MGLY + 0.85 HAC + 0.08 CH2O ', & ! index 428
     '  MACRNO2 + HO2 --> 0.93 CO2 + 0.15 POx + 0.07 HCOOH + 0.08 ACTA + 0.07 MGLY + 0.85 HAC + 0.08 CH2O ', & ! index 429
     '  MACRNO2 + NO2 --> LOx + PMNN                                                                      ', & ! index 430
     '           PMNN --> POx + MACRNO2 + NO2                                                             ', & ! index 431
     '     DHMOB + OH --> 1.5 PCO + 0.5 HAC + 0.5 MEK + HO2 + 1.5 CO                                      ', & ! index 432
     '     DIBOO + NO --> POx + 0.48 GLYX + 0.52 GLYC + 0.52 MGLY + 0.48 HAC + HO2 + NO2                  ', & ! index 433
     '     DIBOO + NO --> POx + HNO3                                                                      ', & ! index 434
     '    DIBOO + HO2 --> 0.85 R4P + 0.072 GLYX + 0.078 GLYC + 0.078 MGLY + 0.072 HAC + 0.15 HO2 + 0.15 OH', & ! index 435
     '      MOBA + OH --> MOBAOO                                                                          ', & ! index 436
     '    MOBAOO + NO --> CO2 + POx + RCHO + HO2 + NO2                                                    ', & ! index 437
     '    MOBAOO + NO --> POx + HNO3                                                                      ', & ! index 438
     '   MOBAOO + HO2 --> 0.5 CO2 + 0.5 R4P + 0.5 RCHO + 0.5 HO2 + 0.5 OH                                 ', & ! index 439
     '      MOBA + O3 --> CO2 + LOx + MEK + HO2 + OH                                                      ', & ! index 440
     '     ETHLN + OH --> CO2 + CH2O + NO2                                                                ', & ! index 441
     '    PROPNN + OH --> MGLY + NO2                                                                      ', & ! index 442
     '     CH2OO + NO --> POx + CH2O + NO2                                                                ', & ! index 443
     '    CH2OO + NO2 --> POx + CH2O + NO3                                                                ', & ! index 444
     '    CH2OO + SO2 --> PSO4 + SO4 + CH2O                                                               ', & ! index 445
     '    CH2OO + H2O --> H2O2 + CH2O                                                                     ', & ! index 446
     '    CH2OO + H2O --> HCOOH                                                                           ', & ! index 447
     '    MACROO + CO --> LCO + MACR                                                                      ', & ! index 448
     '    MACROO + NO --> POx + MACR + NO2                                                                ', & ! index 449
     '   MACROO + NO2 --> POx + MACR + NO3                                                                ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_15 = (/ &
     '   MACROO + SO2 --> PSO4 + SO4 + MACR                                                               ', & ! index 451
     '   MACROO + H2O --> MRP                                                                             ', & ! index 452
     '   MACROO + H2O --> H2O2 + MACR                                                                     ', & ! index 453
     '     MVKOO + CO --> LCO + MVK                                                                       ', & ! index 454
     '     MVKOO + NO --> POx + MVK + NO2                                                                 ', & ! index 455
     '    MVKOO + NO2 --> POx + MVK + NO3                                                                 ', & ! index 456
     '    MVKOO + SO2 --> PSO4 + SO4 + MVK                                                                ', & ! index 457
     '    MVKOO + H2O --> H2O2 + MVK                                                                      ', & ! index 458
     '    MGLYOO + CO --> LCO + MGLY                                                                      ', & ! index 459
     '    MGLYOO + NO --> POx + MGLY + NO2                                                                ', & ! index 460
     '   MGLYOO + NO2 --> POx + MGLY + NO3                                                                ', & ! index 461
     '   MGLYOO + SO2 --> PSO4 + SO4 + MGLY                                                               ', & ! index 462
     '   MGLYOO + H2O --> H2O2 + MGLY                                                                     ', & ! index 463
     '     MGLOO + CO --> LCO + MGLY                                                                      ', & ! index 464
     '     MGLOO + NO --> POx + MGLY + NO2                                                                ', & ! index 465
     '    MGLOO + NO2 --> POx + MGLY + NO3                                                                ', & ! index 466
     '    MGLOO + SO2 --> PSO4 + SO4 + MGLY                                                               ', & ! index 467
     '    MGLOO + H2O --> MCO3 + MO2                                                                      ', & ! index 468
     '    MGLOO + H2O --> H2O2 + MGLY                                                                     ', & ! index 469
     '   CH3CHOO + CO --> LCO + ALD2                                                                      ', & ! index 470
     '   CH3CHOO + NO --> POx + ALD2 + NO2                                                                ', & ! index 471
     '  CH3CHOO + NO2 --> POx + ALD2 + NO3                                                                ', & ! index 472
     '  CH3CHOO + SO2 --> PSO4 + SO4 + ALD2                                                               ', & ! index 473
     '  CH3CHOO + H2O --> H2O2 + ALD2                                                                     ', & ! index 474
     '  CH3CHOO + H2O --> ACTA                                                                            ', & ! index 475
     '      GAOO + CO --> LCO + GLYC                                                                      ', & ! index 476
     '      GAOO + NO --> POx + GLYC + NO2                                                                ', & ! index 477
     '     GAOO + NO2 --> POx + GLYC + NO3                                                                ', & ! index 478
     '     GAOO + SO2 --> PSO4 + SO4 + GLYC                                                               ', & ! index 479
     '     GAOO + H2O --> H2O2 + GLYC                                                                     ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_16 = (/ &
     '     GAOO + H2O --> HAC                                                                             ', & ! index 481
     '      BENZ + OH --> BRO2 + 0.252 GLYX + 1.92 CH2O + OH                                              ', & ! index 482
     '      TOLU + OH --> TRO2 + 0.26 GLYX + 0.215 MGLY + 1.92 CH2O + OH                                  ', & ! index 483
     '      XYLE + OH --> XRO2 + 0.268 GLYX + 0.463 MGLY + 1.92 CH2O + OH                                 ', & ! index 484
     '     XYLE + NO3 --> CO2 + 2 LOx                                                                     ', & ! index 485
     '     BRO2 + HO2 --> LBRO2H                                                                          ', & ! index 486
     '      BRO2 + NO --> LBRO2N                                                                          ', & ! index 487
     '     TRO2 + HO2 --> LTRO2H                                                                          ', & ! index 488
     '      TRO2 + NO --> LTRO2N                                                                          ', & ! index 489
     '     XRO2 + HO2 --> LXRO2H                                                                          ', & ! index 490
     '      XRO2 + NO --> LXRO2N                                                                          ', & ! index 491
     '      MTPA + OH --> PIO2                                                                            ', & ! index 492
     '      MTPO + OH --> PIO2                                                                            ', & ! index 493
     '      PIO2 + NO --> 0.82 POx + 0.12 MONITS + 0.06 MONITU + 0.07 HCOOH + 0.11 ACET + 0.43 RCHO + 0.44', & ! index 494
     '     PIO2 + HO2 --> PIP                                                                             ', & ! index 495
     '     PIO2 + MO2 --> 0.25 ROH + 0.75 RCHO + 0.75 MEK + 0.75 CH2O + HO2 + 0.25 MOH                    ', & ! index 496
     '    PIO2 + MCO3 --> RCHO + MEK + 0.5 HO2 + 0.5 MO2 + RCOOH                                          ', & ! index 497
     '     PIO2 + NO3 --> LOx + RCHO + MEK + HO2 + NO2                                                    ', & ! index 498
     '      MTPA + O3 --> LOx + 0.14 PCO + 0.02 H2O2 + 0.62 KO2 + 0.65 RCHO + 0.53 MEK + 0.1 HO2 + 0.85 OH', & ! index 499
     '      MTPO + O3 --> LOx + 0.14 PCO + 0.02 H2O2 + 0.62 KO2 + 0.65 RCHO + 0.53 MEK + 0.1 HO2 + 0.85 OH', & ! index 500
     '     MTPA + NO3 --> 2 LOx + 0.9 OLND + 0.1 OLNN                                                     ', & ! index 501
     '     MTPO + NO3 --> 2 LOx + 0.9 OLND + 0.1 OLNN                                                     ', & ! index 502
     '      LIMO + OH --> LIMO2                                                                           ', & ! index 503
     '      LIMO + O3 --> LOx + 0.14 PCO + 0.02 H2O2 + 0.01 HCOOH + 0.42 KO2 + 0.16 ETO2 + 0.46 PRPE + 0.7', & ! index 504
     '     LIMO + NO3 --> 2 LOx + 0.5 OLND + 0.5 OLNN                                                     ', & ! index 505
     '     LIMO2 + NO --> 0.78 POx + 0.22 MONITU + 0.058 HAC + 0.289 PRPE + 0.491 RCHO + 0.289 MEK + 0.231', & ! index 506
     '    LIMO2 + HO2 --> PIP                                                                             ', & ! index 507
     '    LIMO2 + MO2 --> 0.25 ROH + 0.192 PRPE + 0.308 MACR + 1.04 CH2O + HO2 + 0.25 MOH                 ', & ! index 508
     '   LIMO2 + MCO3 --> 0.192 PRPE + 0.308 MACR + 0.385 CH2O + 0.5 HO2 + 0.5 MO2 + 0.5 RCOOH            ', & ! index 509
     '    LIMO2 + NO3 --> LOx + 0.385 PRPE + 0.615 MACR + 0.385 CH2O + HO2 + NO2                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_17 = (/ &
     '       PIP + OH --> 0.44 R4O2 + 0.08 RCHO + 0.41 MEK + 0.49 OH                                      ', & ! index 511
     '      OLNN + NO --> POx + MONITS + HO2 + NO2                                                        ', & ! index 512
     '      OLND + NO --> 2 POx + 1.24 RCHO + 0.464 MEK + 0.287 CH2O + 2 NO2                              ', & ! index 513
     '     OLNN + HO2 --> 0.7 MONITS + 0.3 MONITU                                                         ', & ! index 514
     '     OLND + HO2 --> 0.7 MONITS + 0.3 MONITU                                                         ', & ! index 515
     '     OLNN + MO2 --> 0.7 MONITS + 0.3 MONITU + CH2O + 2 HO2                                          ', & ! index 516
     '     OLND + MO2 --> 0.5 POx + 0.25 ROH + 0.35 MONITS + 0.15 MONITU + 0.93 RCHO + 0.348 MEK + 0.965 C', & ! index 517
     '    OLNN + MCO3 --> 0.7 MONITS + 0.3 MONITU + HO2 + MO2                                             ', & ! index 518
     '    OLND + MCO3 --> POx + 1.24 RCHO + 0.464 MEK + 0.287 CH2O + 0.5 MO2 + NO2 + 0.5 RCOOH            ', & ! index 519
     '     OLNN + NO3 --> LOx + 0.7 MONITS + 0.3 MONITU + HO2 + NO2                                       ', & ! index 520
     '     OLND + NO3 --> 1.24 RCHO + 0.464 MEK + 0.287 CH2O + 2 NO2                                      ', & ! index 521
     '         2 OLNN --> 1.4 MONITS + 0.6 MONITU + HO2                                                   ', & ! index 522
     '    OLND + OLNN --> 0.5 POx + 1.05 MONITS + 0.45 MONITU + 0.64 RCHO + 0.149 MEK + 0.202 CH2O + 0.5 H', & ! index 523
     '         2 OLND --> POx + 0.7 MONITS + 0.3 MONITU + 1.21 RCHO + 0.285 MEK + 0.504 CH2O + NO2        ', & ! index 524
     '    MONITS + OH --> HONIT                                                                           ', & ! index 525
     '    MONITU + OH --> HONIT                                                                           ', & ! index 526
     '    MONITU + O3 --> LOx + HONIT                                                                     ', & ! index 527
     '   MONITU + NO3 --> 2 LOx + HONIT                                                                   ', & ! index 528
     '   MONITS + NO3 --> 2 LOx + HONIT                                                                   ', & ! index 529
     '         IONITA --> INDIOL + POx + HNO3                                                             ', & ! index 530
     '         MONITA --> INDIOL + POx + HNO3                                                             ', & ! index 531
     '     HONIT + OH --> 2 POx + HAC + NO3                                                               ', & ! index 532
     '     HC187 + OH --> 0.5 PCO + 0.5 MGLY + CH2O + 0.5 MCO3 + 0.5 HO2 + 0.5 CO                         ', & ! index 533
     '     HPALD + OH --> 0.085 CO2 + 0.55 PCO + 0.365 HPC52O2 + 0.085 GLYX + 0.55 MGLY + 0.55 CH2O + 0.08', & ! index 534
     '   DHPCARP + NO --> POx + GLYX + MGLY + OH + NO2                                                    ', & ! index 535
     '   HPC52O2 + NO --> POx + GLYX + MGLY + OH + NO2                                                    ', & ! index 536
     '  DHPCARP + HO2 --> RCOOH                                                                           ', & ! index 537
     '  HPC52O2 + HO2 --> RCOOH                                                                           ', & ! index 538
     '        DHPCARP --> PCO + OH + CO + RCOOH                                                           ', & ! index 539
     '        DHPCARP --> DHDC                                                                            ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_18 = (/ &
     '            HO2 --> O2                                                                              ', & ! index 541
     '            NO2 --> 0.5 LOx + 0.5 HNO2 + 0.5 HNO3                                                   ', & ! index 542
     '            NO3 --> LOx + HNO3                                                                      ', & ! index 543
     '     N2O5 + H2O --> LOx + 2 HNO3                                                                    ', & ! index 544
     '     N2O5 + HCl --> LOx + ClNO2 + HNO3                                                              ', & ! index 545
     '           N2O5 --> LOx + ClNO2 + HNO3                                                              ', & ! index 546
     '    BrNO3 + H2O --> HOBr + HNO3                                                                     ', & ! index 547
     '    BrNO3 + HCl --> LOx + BrCl + HNO3                                                               ', & ! index 548
     '    ClNO3 + H2O --> HNO3 + HOCl                                                                     ', & ! index 549
     '    ClNO3 + HCl --> LOx + Cl2 + HNO3                                                                ', & ! index 550
     '    ClNO3 + HBr --> LOx + BrCl + HNO3                                                               ', & ! index 551
     ' BrSALA + ClNO3 --> LOx + BrCl + HNO3                                                               ', & ! index 552
     ' BrSALC + ClNO3 --> LOx + BrCl + HNO3                                                               ', & ! index 553
     '     HOCl + HCl --> LOx + Cl2 + H2O                                                                 ', & ! index 554
     '     HOCl + HBr --> LOx + BrCl + H2O                                                                ', & ! index 555
     '     HOBr + HBr --> LOx + Br2 + H2O                                                                 ', & ! index 556
     '     HOBr + HCl --> LOx + BrCl + H2O                                                                ', & ! index 557
     '           HOBr --> LOx + BrCl + H2O                                                                ', & ! index 558
     '  BrSALA + HOBr --> LOx + Br2                                                                       ', & ! index 559
     '  BrSALC + HOBr --> LOx + Br2                                                                       ', & ! index 560
     '           HOBr --> SO4H1 + LOx + HBr                                                               ', & ! index 561
     '           HOBr --> SO4H2 + LOx + HBr                                                               ', & ! index 562
     '            HCl --> O2                                                                              ', & ! index 563
     '            HCl --> O2                                                                              ', & ! index 564
     '       HBr + O3 --> HOBr                                                                            ', & ! index 565
     '    BrSALA + O3 --> HOBr                                                                            ', & ! index 566
     '    BrSALC + O3 --> HOBr                                                                            ', & ! index 567
     '            HBr --> BrSALA                                                                          ', & ! index 568
     '            HBr --> BrSALC                                                                          ', & ! index 569
     '             HI --> AERI                                                                            ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_19 = (/ &
     '             HI --> ISALA                                                                           ', & ! index 571
     '             HI --> ISALC                                                                           ', & ! index 572
     '            HOI --> ISALA + LOx                                                                     ', & ! index 573
     '            HOI --> ISALC + LOx                                                                     ', & ! index 574
     '           I2O2 --> 2 AERI + 2 LOx                                                                  ', & ! index 575
     '           I2O2 --> 2 ISALA + 2 LOx                                                                 ', & ! index 576
     '           I2O2 --> 2 ISALC + 2 LOx                                                                 ', & ! index 577
     '           I2O3 --> 2 AERI + 3 LOx                                                                  ', & ! index 578
     '           I2O3 --> 2 ISALA + 3 LOx                                                                 ', & ! index 579
     '           I2O3 --> 2 ISALC + 3 LOx                                                                 ', & ! index 580
     '           I2O4 --> 2 AERI + 4 LOx                                                                  ', & ! index 581
     '           I2O4 --> 2 ISALA + 4 LOx                                                                 ', & ! index 582
     '           I2O4 --> 2 ISALC + 4 LOx                                                                 ', & ! index 583
     '           IONO --> ISALA + LOx                                                                     ', & ! index 584
     '           IONO --> ISALC + LOx                                                                     ', & ! index 585
     '          IONO2 --> ISALA + 2 LOx                                                                   ', & ! index 586
     '          IONO2 --> ISALC + 2 LOx                                                                   ', & ! index 587
     '           IONO --> LOx + 0.15 IBr + 0.85 ICl + HNO2                                                ', & ! index 588
     '          IONO2 --> LOx + 0.15 IBr + 0.85 ICl + HNO3                                                ', & ! index 589
     '            HOI --> LOx + 0.15 IBr + 0.85 ICl                                                       ', & ! index 590
     '           GLYX --> SOAGX                                                                           ', & ! index 591
     '           MGLY --> SOAMG                                                                           ', & ! index 592
     '         IEPOXA --> SOAIE                                                                           ', & ! index 593
     '         IEPOXB --> SOAIE                                                                           ', & ! index 594
     '         IEPOXD --> SOAIE                                                                           ', & ! index 595
     '           IMAE --> SOAME                                                                           ', & ! index 596
     '           LVOC --> LVOCOA                                                                          ', & ! index 597
     '         ISN1OG --> ISN1OA                                                                          ', & ! index 598
     '         ISOPND --> LOx + IONITA                                                                    ', & ! index 599
     '         ISOPNB --> LOx + IONITA                                                                    ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_20 = (/ &
     '          MACRN --> LOx + IONITA                                                                    ', & ! index 601
     '           MVKN --> LOx + IONITA                                                                    ', & ! index 602
     '           R4N2 --> LOx + IONITA                                                                    ', & ! index 603
     '           DHDN --> IONITA                                                                          ', & ! index 604
     '         MONITS --> MONITA                                                                          ', & ! index 605
     '         MONITU --> MONITA                                                                          ', & ! index 606
     '          HONIT --> MONITA                                                                          ', & ! index 607
     '             O3 --> O + O2                                                                          ', & ! index 608
     '             O3 --> O1D + O2                                                                        ', & ! index 609
     '             O2 --> 2 POx + 2 O                                                                     ', & ! index 610
     '            NO2 --> NO + O                                                                          ', & ! index 611
     '           H2O2 --> 2 OH                                                                            ', & ! index 612
     '             MP --> CH2O + HO2 + OH                                                                 ', & ! index 613
     '           CH2O --> PCO + H + HO2 + CO                                                              ', & ! index 614
     '           CH2O --> PCO + CO + H2                                                                   ', & ! index 615
     '           HNO3 --> OH + NO2                                                                        ', & ! index 616
     '           HNO2 --> NO + OH                                                                         ', & ! index 617
     '           HNO4 --> POx + NO3 + OH                                                                  ', & ! index 618
     '           HNO4 --> HO2 + NO2                                                                       ', & ! index 619
     '            NO3 --> O + NO2                                                                         ', & ! index 620
     '            NO3 --> 2 LOx + NO + O2                                                                 ', & ! index 621
     '           N2O5 --> NO3 + NO2                                                                       ', & ! index 622
     '           ALD2 --> 0.88 PCO + 0.12 MCO3 + HO2 + 0.88 MO2 + 0.88 CO                                 ', & ! index 623
     '           ALD2 --> PCO + CH4 + CO                                                                  ', & ! index 624
     '            PAN --> 0.3 POx + 0.7 MCO3 + 0.3 NO3 + 0.3 MO2 + 0.7 NO2                                ', & ! index 625
     '           RCHO --> PCO + ETO2 + HO2 + CO                                                           ', & ! index 626
     '           ACET --> MCO3 + MO2                                                                      ', & ! index 627
     '           ACET --> PCO + 2 MO2 + CO                                                                ', & ! index 628
     '            MEK --> 0.15 RCO3 + 0.85 ETO2 + 0.85 MCO3 + 0.15 MO2                                    ', & ! index 629
     '           GLYC --> PCO + 0.9 CH2O + 1.73 HO2 + 0.07 OH + CO + 0.1 MOH                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_21 = (/ &
     '           GLYX --> 2 PCO + 2 HO2 + 2 CO                                                            ', & ! index 631
     '           GLYX --> 2 PCO + 2 CO + H2                                                               ', & ! index 632
     '           GLYX --> PCO + CH2O + CO                                                                 ', & ! index 633
     '           MGLY --> PCO + MCO3 + HO2 + CO                                                           ', & ! index 634
     '            MVK --> PCO + PRPE + CO                                                                 ', & ! index 635
     '            MVK --> PCO + CH2O + MCO3 + HO2 + CO                                                    ', & ! index 636
     '            MVK --> RCO3 + MO2                                                                      ', & ! index 637
     '           MACR --> PCO + CH2O + MCO3 + HO2 + CO                                                    ', & ! index 638
     '            HAC --> CH2O + MCO3 + HO2                                                               ', & ! index 639
     '           INPN --> RCHO + HO2 + OH + NO2                                                           ', & ! index 640
     '           PRPN --> RCHO + HO2 + OH + NO2                                                           ', & ! index 641
     '            ETP --> ALD2 + HO2 + OH                                                                 ', & ! index 642
     '           RA3P --> RCHO + HO2 + OH                                                                 ', & ! index 643
     '           RB3P --> ACET + HO2 + OH                                                                 ', & ! index 644
     '            R4P --> RCHO + HO2 + OH                                                                 ', & ! index 645
     '             PP --> CH2O + ALD2 + HO2 + OH                                                          ', & ! index 646
     '             RP --> ALD2 + HO2 + OH                                                                 ', & ! index 647
     '           RIPA --> 0.005 LVOC + 0.275 HC5 + 0.285 MACR + 0.71 CH2O + 0.425 MVK + 0.985 HO2 + 0.985 ', & ! index 648
     '           RIPB --> 0.005 LVOC + 0.275 HC5 + 0.285 MACR + 0.71 CH2O + 0.425 MVK + 0.985 HO2 + 0.985 ', & ! index 649
     '           RIPD --> 0.005 LVOC + 0.275 HC5 + 0.285 MACR + 0.71 CH2O + 0.425 MVK + 0.985 HO2 + 0.985 ', & ! index 650
     '            IAP --> 0.67 PCO + 0.26 GLYC + 0.58 MGLY + 0.36 HAC + HO2 + OH + 0.67 CO + 0.19 H2      ', & ! index 651
     '           ISNP --> RCHO + HO2 + OH + NO2                                                           ', & ! index 652
     '            VRP --> 0.7 GLYC + 0.3 MGLY + 0.3 CH2O + 0.7 MCO3 + 0.3 HO2 + OH                        ', & ! index 653
     '            MRP --> 0.5 PCO + HAC + 0.5 CH2O + HO2 + OH + 0.5 CO                                    ', & ! index 654
     '           MAOP --> CH2O + MCO3 + OH                                                                ', & ! index 655
     '           R4N2 --> 0.05 A3O2 + 0.18 B3O2 + 0.32 ACET + 0.32 ETO2 + 0.13 RCHO + 0.19 MEK + 0.32 ALD2', & ! index 656
     '            MAP --> MO2 + OH                                                                        ', & ! index 657
     '          MACRN --> 0.5 PCO + MGLY + HAC + 0.5 CH2O + HO2 + NO2 + 0.5 CO                            ', & ! index 658
     '           MVKN --> GLYC + MCO3 + NO2                                                               ', & ! index 659
     '         ISOPNB --> HC5 + HO2 + NO2                                                                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_22 = (/ &
     '            Br2 --> 2 Br                                                                            ', & ! index 661
     '            BrO --> Br + O                                                                          ', & ! index 662
     '           HOBr --> LOx + Br + OH                                                                   ', & ! index 663
     '          BrNO3 --> Br + NO3                                                                        ', & ! index 664
     '          BrNO3 --> BrO + NO2                                                                       ', & ! index 665
     '          BrNO2 --> Br + NO2                                                                        ', & ! index 666
     '          CHBr3 --> 3 Br                                                                            ', & ! index 667
     '         CH2Br2 --> 2 Br                                                                            ', & ! index 668
     '          CH3Br --> Br + MO2                                                                        ', & ! index 669
     '          CH3Cl --> MO2 + Cl                                                                        ', & ! index 670
     '         CH2Cl2 --> 2 Cl                                                                            ', & ! index 671
     '           BrCl --> Br + Cl                                                                         ', & ! index 672
     '            Cl2 --> 2 Cl                                                                            ', & ! index 673
     '            ClO --> O + Cl                                                                          ', & ! index 674
     '           OClO --> ClO + O                                                                         ', & ! index 675
     '          Cl2O2 --> 2 LOx + ClOO + Cl                                                               ', & ! index 676
     '          ClNO2 --> NO2 + Cl                                                                        ', & ! index 677
     '          ClNO3 --> NO3 + Cl                                                                        ', & ! index 678
     '          ClNO3 --> ClO + NO2                                                                       ', & ! index 679
     '           HOCl --> LOx + OH + Cl                                                                   ', & ! index 680
     '        CH3CCl3 --> 3 Cl                                                                            ', & ! index 681
     '           CCl4 --> 4 Cl                                                                            ', & ! index 682
     '          CFC11 --> 3 Cl                                                                            ', & ! index 683
     '          CFC12 --> 2 Cl                                                                            ', & ! index 684
     '         CFC113 --> 3 Cl                                                                            ', & ! index 685
     '         CFC114 --> 2 Cl                                                                            ', & ! index 686
     '         CFC115 --> Cl                                                                              ', & ! index 687
     '        HCFC123 --> 2 Cl                                                                            ', & ! index 688
     '       HCFC141b --> 2 Cl                                                                            ', & ! index 689
     '       HCFC142b --> 2 Cl                                                                            ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_23 = (/ &
     '         HCFC22 --> 2 Cl                                                                            ', & ! index 691
     '          H1301 --> Br                                                                              ', & ! index 692
     '          H1211 --> Br + Cl                                                                         ', & ! index 693
     '          H2402 --> 2 Br                                                                            ', & ! index 694
     '           ClOO --> Cl + O2                                                                         ', & ! index 695
     '             I2 --> 2 I                                                                             ', & ! index 696
     '            HOI --> LOx + I + OH                                                                    ', & ! index 697
     '             IO --> I + O                                                                           ', & ! index 698
     '            OIO --> 2 LOx + I + O2                                                                  ', & ! index 699
     '            INO --> I + NO                                                                          ', & ! index 700
     '           IONO --> I + NO2                                                                         ', & ! index 701
     '          IONO2 --> I + NO3                                                                         ', & ! index 702
     '           I2O2 --> OIO + I                                                                         ', & ! index 703
     '           CH3I --> I                                                                               ', & ! index 704
     '          CH2I2 --> 2 I                                                                             ', & ! index 705
     '         CH2ICl --> I + Cl                                                                          ', & ! index 706
     '         CH2IBr --> I + Br                                                                          ', & ! index 707
     '           I2O4 --> 2 OIO                                                                           ', & ! index 708
     '           I2O3 --> OIO + IO                                                                        ', & ! index 709
     '            IBr --> I + Br                                                                          ', & ! index 710
     '            ICl --> I + Cl                                                                          ', & ! index 711
     '            MPN --> POx + CH2O + HO2 + NO3                                                          ', & ! index 712
     '            MPN --> MO2 + NO2                                                                       ', & ! index 713
     '         ISOPND --> HC5 + HO2 + NO2                                                                 ', & ! index 714
     '         PROPNN --> PCO + CH2O + MO2 + NO2 + CO                                                     ', & ! index 715
     '          ATOOH --> CH2O + MCO3 + OH                                                                ', & ! index 716
     '            N2O --> POx + O1D + N2                                                                  ', & ! index 717
     '            OCS --> PCO + SO2 + CO                                                                  ', & ! index 718
     '            SO4 --> SO2 + 2 OH                                                                      ', & ! index 719
     '             NO --> POx + N + O                                                                     ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(9) :: EQN_NAMES_24 = (/ &
     '            PIP --> RCHO + HO2 + OH                                                                 ', & ! index 721
     '           IPMN --> 0.4 CO2 + 0.4 POx + 0.6 IMAO3 + 0.4 CH2O + 0.4 MCO3 + 0.4 NO3 + 0.6 NO2         ', & ! index 722
     '          ETHLN --> PCO + CH2O + HO2 + NO2 + CO                                                     ', & ! index 723
     '           DHDC --> GLYX + MGLY + 2 OH                                                              ', & ! index 724
     '          HPALD --> 1.89 PCO + 0.11 GLYC + 0.5 MGLY + 0.39 HAC + 0.11 MCO3 + 0.89 HO2 + 2 OH + 1.89 ', & ! index 725
     '           ISN1 --> 0.25 GLYX + 0.5 GLYC + 0.25 MGLY + 0.5 HAC + CH2O + HO2 + NO2                   ', & ! index 726
     '         MONITS --> POx + MEK + NO2                                                                 ', & ! index 727
     '         MONITU --> POx + RCHO + NO2                                                                ', & ! index 728
     '          HONIT --> POx + HAC + NO2                                                                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(729) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4, &
    EQN_NAMES_5, EQN_NAMES_6, EQN_NAMES_7, EQN_NAMES_8, EQN_NAMES_9, &
    EQN_NAMES_10, EQN_NAMES_11, EQN_NAMES_12, EQN_NAMES_13, EQN_NAMES_14, &
    EQN_NAMES_15, EQN_NAMES_16, EQN_NAMES_17, EQN_NAMES_18, EQN_NAMES_19, &
    EQN_NAMES_20, EQN_NAMES_21, EQN_NAMES_22, EQN_NAMES_23, EQN_NAMES_24 /)

  CHARACTER(LEN=15), PARAMETER, DIMENSION(6) :: FAM_NAMES = (/ &
     'POx            ','LOx            ','PCO            ', & ! index 1 - 3
     'LCO            ','PSO4           ','LCH4           ' /)

! INLINED global variables

! End INLINED global variables


END MODULE gckpp_Monitor
