! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Jacobian Data Structures File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_JacobianSP.f90
! Time                 : Fri Sep 14 17:05:59 2018
! Working directory    : /n/regal/mickley_lab/lshen/Code.v11-02c_HGI/KPP/test
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_JacobianSP

  PUBLIC
  SAVE


! Sparse Jacobian Data


  INTEGER, PARAMETER, DIMENSION(30) :: LU_IROW = (/ &
       1,  1,  1,  2,  2,  3,  3,  3,  4,  4,  5,  5, & ! index 1 - 12
       6,  6,  7,  7,  7,  8,  8,  8,  8,  8,  8,  9, & ! index 13 - 24
       9,  9, 10, 10, 10, 10 /)

  INTEGER, PARAMETER, DIMENSION(30) :: LU_ICOL = (/ &
       1,  5,  8,  2,  9,  3,  7,  8,  4,  9,  5,  8, & ! index 1 - 12
       6,  8,  6,  7,  8,  5,  6,  7,  8,  9, 10,  8, & ! index 13 - 24
       9, 10,  5,  8,  9, 10 /)

  INTEGER, PARAMETER, DIMENSION(11) :: LU_CROW = (/ &
       1,  4,  6,  9, 11, 13, 15, 18, 24, 27, 31 /)

  INTEGER, PARAMETER, DIMENSION(11) :: LU_DIAG = (/ &
       1,  4,  6,  9, 11, 13, 16, 21, 25, 30, 31 /)


END MODULE gckpp_JacobianSP

