! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The ODE Jacobian of Chemical Model File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_Jacobian.f90
! Time                 : Sat Sep 22 13:46:13 2018
! Working directory    : /n/regal/mickley_lab/lshen/Code.v11-02c_HGI/KPP/test
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Jacobian

  USE gckpp_Parameters
  USE gckpp_JacobianSP

  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Jac_SP - the Jacobian of Variables in sparse matrix representation
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local)
!      JVS       - sparse Jacobian of variables
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Jac_SP ( V, F, RCT, JVS )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)


! Local variables
! B - Temporary array
  REAL(kind=dp) :: B(11)

! B(1) = dA(1)/dV(6)
  B(1) = RCT(1)*V(8)
! B(2) = dA(1)/dV(8)
  B(2) = RCT(1)*V(6)
! B(3) = dA(2)/dV(8)
  B(3) = RCT(2)*V(9)
! B(4) = dA(2)/dV(9)
  B(4) = RCT(2)*V(8)
! B(5) = dA(3)/dV(8)
  B(5) = RCT(3)*V(10)
! B(6) = dA(3)/dV(10)
  B(6) = RCT(3)*V(8)
! B(7) = dA(4)/dV(7)
  B(7) = RCT(4)*V(8)
! B(8) = dA(4)/dV(8)
  B(8) = RCT(4)*V(7)
! B(9) = dA(5)/dV(5)
  B(9) = RCT(5)*V(8)
! B(10) = dA(5)/dV(8)
  B(10) = RCT(5)*V(5)
! B(11) = dA(6)/dV(9)
  B(11) = RCT(6)*2*V(9)

! Construct the Jacobian terms from B's
! JVS(1) = Jac_FULL(1,1)
  JVS(1) = 0
! JVS(2) = Jac_FULL(1,5)
  JVS(2) = B(9)
! JVS(3) = Jac_FULL(1,8)
  JVS(3) = B(10)
! JVS(4) = Jac_FULL(2,2)
  JVS(4) = 0
! JVS(5) = Jac_FULL(2,9)
  JVS(5) = B(11)
! JVS(6) = Jac_FULL(3,3)
  JVS(6) = 0
! JVS(7) = Jac_FULL(3,7)
  JVS(7) = B(7)
! JVS(8) = Jac_FULL(3,8)
  JVS(8) = B(8)
! JVS(9) = Jac_FULL(4,4)
  JVS(9) = 0
! JVS(10) = Jac_FULL(4,9)
  JVS(10) = B(11)
! JVS(11) = Jac_FULL(5,5)
  JVS(11) = -B(9)
! JVS(12) = Jac_FULL(5,8)
  JVS(12) = -B(10)
! JVS(13) = Jac_FULL(6,6)
  JVS(13) = -B(1)
! JVS(14) = Jac_FULL(6,8)
  JVS(14) = -B(2)
! JVS(15) = Jac_FULL(7,6)
  JVS(15) = B(1)
! JVS(16) = Jac_FULL(7,7)
  JVS(16) = -B(7)
! JVS(17) = Jac_FULL(7,8)
  JVS(17) = B(2)-B(8)
! JVS(18) = Jac_FULL(8,5)
  JVS(18) = -B(9)
! JVS(19) = Jac_FULL(8,6)
  JVS(19) = -B(1)
! JVS(20) = Jac_FULL(8,7)
  JVS(20) = -B(7)
! JVS(21) = Jac_FULL(8,8)
  JVS(21) = -B(2)-B(3)-B(5)-B(8)-B(10)
! JVS(22) = Jac_FULL(8,9)
  JVS(22) = -B(4)
! JVS(23) = Jac_FULL(8,10)
  JVS(23) = -B(6)
! JVS(24) = Jac_FULL(9,8)
  JVS(24) = -B(3)+B(5)
! JVS(25) = Jac_FULL(9,9)
  JVS(25) = -B(4)-2*B(11)
! JVS(26) = Jac_FULL(9,10)
  JVS(26) = B(6)
! JVS(27) = Jac_FULL(10,5)
  JVS(27) = B(9)
! JVS(28) = Jac_FULL(10,8)
  JVS(28) = B(3)-B(5)+B(10)
! JVS(29) = Jac_FULL(10,9)
  JVS(29) = B(4)
! JVS(30) = Jac_FULL(10,10)
  JVS(30) = -B(6)
      
END SUBROUTINE Jac_SP

! End of Jac_SP function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Jac_SP_Vec - function for sparse multiplication: sparse Jacobian times vector
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      UV        - User vector for variables
!      JUV       - Jacobian times user vector
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Jac_SP_Vec ( JVS, UV, JUV )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! UV - User vector for variables
  REAL(kind=dp) :: UV(NVAR)
! JUV - Jacobian times user vector
  REAL(kind=dp) :: JUV(NVAR)

  JUV(1) = JVS(1)*UV(1)+JVS(2)*UV(5)+JVS(3)*UV(8)
  JUV(2) = JVS(4)*UV(2)+JVS(5)*UV(9)
  JUV(3) = JVS(6)*UV(3)+JVS(7)*UV(7)+JVS(8)*UV(8)
  JUV(4) = JVS(9)*UV(4)+JVS(10)*UV(9)
  JUV(5) = JVS(11)*UV(5)+JVS(12)*UV(8)
  JUV(6) = JVS(13)*UV(6)+JVS(14)*UV(8)
  JUV(7) = JVS(15)*UV(6)+JVS(16)*UV(7)+JVS(17)*UV(8)
  JUV(8) = JVS(18)*UV(5)+JVS(19)*UV(6)+JVS(20)*UV(7)+JVS(21)*UV(8)+JVS(22)*UV(9)+JVS(23)*UV(10)
  JUV(9) = JVS(24)*UV(8)+JVS(25)*UV(9)+JVS(26)*UV(10)
  JUV(10) = JVS(27)*UV(5)+JVS(28)*UV(8)+JVS(29)*UV(9)+JVS(30)*UV(10)
      
END SUBROUTINE Jac_SP_Vec

! End of Jac_SP_Vec function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! JacTR_SP_Vec - sparse multiplication: sparse Jacobian transposed times vector
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      UV        - User vector for variables
!      JTUV      - Jacobian transposed times user vector
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE JacTR_SP_Vec ( JVS, UV, JTUV )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! UV - User vector for variables
  REAL(kind=dp) :: UV(NVAR)
! JTUV - Jacobian transposed times user vector
  REAL(kind=dp) :: JTUV(NVAR)

  JTUV(1) = JVS(1)*UV(1)
  JTUV(2) = JVS(4)*UV(2)
  JTUV(3) = JVS(6)*UV(3)
  JTUV(4) = JVS(9)*UV(4)
  JTUV(5) = JVS(2)*UV(1)+JVS(11)*UV(5)+JVS(18)*UV(8)+JVS(27)*UV(10)
  JTUV(6) = JVS(13)*UV(6)+JVS(15)*UV(7)+JVS(19)*UV(8)
  JTUV(7) = JVS(7)*UV(3)+JVS(16)*UV(7)+JVS(20)*UV(8)
  JTUV(8) = JVS(3)*UV(1)+JVS(8)*UV(3)+JVS(12)*UV(5)+JVS(14)*UV(6)+JVS(17)*UV(7)+JVS(21)*UV(8)+JVS(24)*UV(9)+JVS(28)&
              &*UV(10)
  JTUV(9) = JVS(5)*UV(2)+JVS(10)*UV(4)+JVS(22)*UV(8)+JVS(25)*UV(9)+JVS(29)*UV(10)
  JTUV(10) = JVS(23)*UV(8)+JVS(26)*UV(9)+JVS(30)*UV(10)
      
END SUBROUTINE JacTR_SP_Vec

! End of JacTR_SP_Vec function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE gckpp_Jacobian

