! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_Monitor.f90
! Time                 : Sat Sep 22 13:46:14 2018
! Working directory    : /n/regal/mickley_lab/lshen/Code.v11-02c_HGI/KPP/test
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Monitor


  CHARACTER(LEN=15), PARAMETER, DIMENSION(11) :: SPC_NAMES = (/ &
     'CH2O           ','H2O            ','NO3            ', & ! index 1 - 3
     'O              ','MO2            ','NO             ', & ! index 4 - 6
     'NO2            ','O3             ','OH             ', & ! index 7 - 9
     'HO2            ','O2             ' /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=15), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(6) :: EQN_NAMES = (/ &
     ' NO + O3 --> NO2 + O2                                                                               ', & ! index 1
     ' O3 + OH --> HO2 + O2                                                                               ', & ! index 2
     'O3 + HO2 --> OH + 2 O2                                                                              ', & ! index 3
     'NO2 + O3 --> NO3 + O2                                                                               ', & ! index 4
     'MO2 + O3 --> CH2O + HO2 + O2                                                                        ', & ! index 5
     '    2 OH --> H2O + O                                                                                ' /)

  CHARACTER(LEN=15), DIMENSION(1) :: FAM_NAMES
! INLINED global variables

! End INLINED global variables


END MODULE gckpp_Monitor
